_base_: default.yaml

model:
  name: DSPF
  config:
    num_pred: 2048

dataset:
  name: PCN

train:
  epochs: 300
  lr: 0.001
  batch_size: 32
  scheduler: step
  step_size: 50
  gamma: 0.7

output_path: results/dspf
