_base_: default.yaml

model:
  name: "FBNetWrapper"
  config: {}

output:
  out_path: "results/fbnet"


# Mixed Precision Compatibility
amp_fp16: false  # CUDA extensions do not support half precision; use fp32
