_base_: default.yaml

model:
  name: "FoldingNet"
  config: {}

output:
  out_path: "results/foldingnet"


# Mixed Precision Compatibility
amp_fp16: true  # All ops support half precision; AMP training possible
