_base_: default.yaml

model:
  name: GeoFormer
  config:
    view_distance: 0.7
    step1: 4
    step2: 8
    merge_points: 512
    local_points: 512
    dataset_name: ShapeNet
    num_pred: 16384
    use_depth: true  # requires dataset with depth images

dataset:
  name: ShapeNet

train:
  epochs: 400
  lr: 0.0002
  batch_size: 32
  scheduler: step
  step_size: 50
  gamma: 0.7

output_path: results/geoformer
