_base_: default.yaml

model:
  name: TEETHM4T_Wrapper
  config:
    num_query: 256
    num_points: 8192
    decoder_type: fc
    global_feature_dim: 1024
    encoder_type: graph
    center_num: [512, 128]
    encoder_config:
      embed_dim: 384
      depth: 6
      num_heads: 6
      k: 8
      n_group: 2
      block_style_list: ['attn-deform', 'attn', 'attn', 'attn', 'attn-deform', 'attn']
      combine_style: concat
    decoder_config:
      embed_dim: 384
      depth: 4
      num_heads: 6
      k: 8
      n_group: 2
      self_attn_block_style_list: ['attn-deform', 'attn', 'attn', 'attn-deform']
      self_attn_combine_style: concat
      cross_attn_block_style_list: ['attn-deform', 'attn', 'attn', 'attn-deform']
      cross_attn_combine_style: concat
    num_pred: 8192

dataset:
  name: PCN

train:
  epochs: 300
  lr: 0.0001
  batch_size: 16
  scheduler: step
  step_size: 50
  gamma: 0.7

output_path: results/teethm4t
